### ISSUE TITLE
Consistency Of Data Structure Access

### ISSUE THREAD

**Issue by jameshopkins** [germtb/seon#1]
The docs suggest that there are two interfaces available when accessing properties (`.` and `?.`), each of which expose a different interface when attempting to access an unretrievable property - returning either a runtime exception or a `Nothing`, respectively.

Firstly, exposing two conceptually different interfaces in this way, seems inappropriate on the grounds that both of these concepts are so disparate. What was the motivation behind providing both of these? Secondly, if the `Nothing` interface remains, then I'd suggest adopting a `Maybe` type, in order to provide a consistent return type, regardless of whether the property is retrievable or not. I don't think it makes sense that it's currently polymorphic in this way.

**Comment by germtb** [comment]
Yes, that is an idea I developed but then changed my mind about it and removed it. I just updated the readme. Thanks for bringing it up.
